### ISSUE TITLE
Add Segment failure when legitimate destination supplied

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#261]
v 1.1.4 (4)
Trip: Sand Dollar Inn & Cottages, [kj246kq0z3plvei5p8h1yd]

With an existing 1-segment trip created (Seattle - Moclips), trying to add a segment to Bend OR supercharger. FWIW, location services disabled.

1. Plan menu  | **Add Segment**
2. **Destination Charger Type**:  _Tesla Superchargers_
3. **Destination**: _Bend_ 
4. Waypoint Charger Type: _Auto_ 
5. Touch **Calculate**

Error dialog displayed:

![new trip error](https://cloud.githubusercontent.com/assets/26678403/25127692/1424c272-23f4-11e7-8c5a-d5c2f834750c.PNG)

**Comment by aesculus** [comment]
This is caused because the user failed to validate the address by selecting one of the locations from the list. I have changed the dialog to read: "You must select a destination from the list!" and also removed the Cancel button.

Fixed in V1.1.4 (5)

**Comment by EVGrokker** [comment]
v 1.1.4 (6)
This is still broken, needs to be reopened.

To recreate:
1. **New Trip**: _Seattle WA_ to _Sand Dollar Inn & Cottages, Moclips WA_, _NEMA 14-50 charger_, _Auto_ selection, **Calculate**
2. **Add Segment**: **Destination Charger Type**: _Tesla Supercharger_, Destination: _Bend Supercharger_ (selected from displayed list after typing Bend)
3. **New Trip Error** dialog displayed, "You must select a destination from the list!"

I did select the destination from the list.

I tried the same sequence again, this time without specifying Tesla Supercharger as a charger type.

4. **Add Segment**: **Destination Charger Type**: _None_, **Destination**: _Bend, OR_
5. **New Trip Error** dialog displayed, "You must select an origin or turn location services on!"

Note that this variation of the New Trip Error dialog has both Cancel and OK buttons, only needs OK. But there's still a problem, as I am supplying a valid destination picked from the list.

It is correct that Location Services are off, so now I'll enable them and try again.

Same error as noted in step 5.

6. Delete app, reinstall 1.1.4 (6) from TestFlight.
7. Try steps 1, 2 and 3 again, same result as noted in step 3 -  **New Trip Error** dialog displayed, "You must select a destination from the list!"
8. Try step 4 again (no supercharger specified), this time adding the segment is successful. 

The error clearly is an interaction between location services and filtering the destination with a supercharger.

**Comment by aesculus** [comment]
How do you find these things?  Anyway there were a bunch of errors in this routine for using a supercharger as a destination. Hope they are fixed now.

Comment if not fixed in V1.1.4 (7)

**Comment by EVGrokker** [comment]
I am ruthlessly, doggedly, insanely persistent. To the annoyance of many friends and family members. :)

**Comment by aesculus** [comment]
And don't sleep. :-)
