### ISSUE TITLE
Creating New Segments Without a Charger Starts Fully Charged

### ISSUE THREAD

**Issue by aesculus** [aesculus/EVTO-App-Feedback#274]
Should start with remaining energy like the round trip (out and back) does.

**Comment by aesculus** [comment]
Right now I am forcing this. After we get V1.1.4 in production I will turn this off.

**Comment by aesculus** [comment]
This should be working now in V1.2 (36)

**Comment by EVGrokker** [comment]
v 1.2.0 (36)

This still appears to be a problem.

>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 1, Rear CC: 0, Bat Life: 94, Payload: 99.79032139994459, PF: 0, SA: 0, Temp: 23.88888888888889 
Device Info: iPhone; CPU iPhone OS 10_3_2 like Mac OS X 
Settings: Reserve SoC:20, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (36) 
IAP: Pro:1, Sub:1 
Location: Unknown 
Trip: Oxford Suites Portland - Jantzen Beach, [ol9w9d4degbtxkaum8e0fn]

I created a trip from Seattle WA - Oxford Suites Portland. I deleted the Centralia SC, which gave me a questionable arrival SoC of 6% (should be 17% in my calculation). Then I added a segment to Bend. The departure SoC from Oxford Suites should be 90%, even though I didn't declare a charger.

And it goes downhill from there.

**Comment by aesculus** [comment]
I validated this now works in V1.2 (64)

**Comment by EVGrokker** [comment]
v 1.2.0 (64)

Trip: Oxford Suites Portland - Jantzen Beach, [ylz3an9psfj2zgeb7ehhnr]
>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 0, Rear CC: 0, Bat Life: 100, Payload: 156, PF: 0, SA: 0, Temp: 21 
Device Info: iPhone; CPU iPhone OS 10_3_3 like Mac OS X 
Settings: Reserve SoC:20, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (64) 
IAP: Pro:1, Sub:1 
Location: Unknown 

Not working for me. I created a trip from Seattle to Oxford Suites in Portland. With the car metrics described above, the arrival SoC was 18%, no charging stops en route.

I then added a segment to Bend, but received an error that no superchargers were available. However, there are two in the Portland area, and the Centralia supercharger available before Portland. The Trip Browser does not show the second segment, even though toggling to the Main screen and back to the Plan screen does show it. 

Manually optimizing does not find the available supercharging either.

The good news is that the second segment does start at 90%.

This is related to #365. This issue can probably be closed, since the beginning of the second segment properly shows 90%. However, there are errors before the you can determine that, since the second segment is not visible at first. I'll reopen #365 with this data.
