### ISSUE TITLE
Edit Segment Details: Possible to set date prior to current date (non-fatal)

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#280]
v 1.1.4 (7)

In the Edit Segment Details dialog, it's possible to set a departure date earlier than today.

It doesn't cause any problems, but on the other hand, if the user accidentally dialed a year earlier than today by accident, you'd probably want to alert them.

Suggest either limiting earliest date to today, or displaying a dialog when it happens and letting them try again.

**Comment by aesculus** [comment]
The app can actually deal with post trips (uses historical weather) so I am ok with that.

I think the solution is to prompt them to make sure that is what they want prior to saving.

**Comment by aesculus** [comment]
Fixed in V1.2 (6). They will get a popup if they change the date to before today and leave/close the control.

**Comment by EVGrokker** [comment]
There's a problem with this dialog, see attached screen shot. It appears that you're trying to use a template that's not being properly loaded.

Suggest this wording:

The starting date for your trip is in the past. EVTO will recalculate your trip using historical weather data.

![date past](https://cloud.githubusercontent.com/assets/26678403/25431956/eba3a8f2-2a3f-11e7-961f-7626e78552d2.PNG)

**Comment by aesculus** [comment]
Fixed in V1.2 (7)

![image](https://cloud.githubusercontent.com/assets/283364/25455976/67ebbb5c-2a86-11e7-841f-6a5b069c0525.png)

**Comment by aesculus** [comment]
Later we will need to add this feature to the New Trip and Edit Trip dialogs too.

**Comment by EVGrokker** [comment]
The popup looks OK, but the logic is not correct. If I set a segment's departure date one day earlier than today's date, the warning is not displayed. If I set the departure date two days earlier, the warning is displayed.

**Comment by aesculus** [comment]
OK.  I was doing it by days and thought you got a day credit for passing Now, but obviously not.  I will take a look at it.

**Comment by aesculus** [comment]
Can you recheck this? I think it was fixed in V1.2 (19)

**Comment by EVGrokker** [comment]
1.2.0 (22) still fails to warn user if day is set one day earlier than today.

**Comment by aesculus** [comment]
OK. I will look into that logic again. So many changes occurred in this routine I was not certain where this ended up.

**Comment by aesculus** [comment]
I think this is fixed now in V1.2 (23). Pesky <= vs just <. :-)
