### ISSUE TITLE
Long press on Globe button pops up Trip options

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#293]
Currently (1.1.4) a long press on the globe zooms the map to show the entire trip, especially useful for multi-segment trips. 

While useful, this interaction is unobvious and undiscoverable.

This enhancement proposal would be to display a pop dialog after a long press (or a Force Press on iOS). Initially, there would be three choices:
- Zoom to Trip
- Edit Trip Details
- Trip Summary

**Comment by aesculus** [comment]
Where would this popup be initiated from? The map itself, the globe icon?

I like the way the globe icon has the two states but except for the help, nobody gets that info.

What about having it show a popup the first time that lets people know it has two states?

**Comment by EVGrokker** [comment]
The proposal is that a long press on the globe (which currently zooms to the entire route) would initiate the popup.

I don't like the idea of the behavior changing after the first time. Users would assume it's broken.

**Comment by aesculus** [comment]
> The proposal is that a long press on the globe (which currently zooms to the entire route) would initiate the popup. 

OK. I was thinking the first tap period, not just the long tap. Just to let them know the icon can do two things.

And why do we want to change the purpose of this icon to one of three options? The other options can be accessed from the menu but this is the only way to zoom the bounds of the trip/segment.

**Comment by EVGrokker** [comment]
I think after you implement the changes to the Segment Inspector that we're going to want direct access to editing segment details from that list. So this would mirror that functionality for the active trip. I think of the on-map buttons as including accelerators for advanced users. There may be menu-based equivalents, but being able to zip around without using the menu is nice.

**Comment by aesculus** [comment]
> There may be menu-based equivalents, but being able to zip around without using the menu is nice.

I agree but I don't think we should steal the function from the globe but come up with additional means for the other two features.

**Comment by EVGrokker** [comment]
Not stealing, overloading. How about this:

Short tap = zoom to active segment (as currently implemented)
Long hold (or force hold) = popup menu with quick select of limited choices.

Selecting Zoom to Trip is equivalent to long hold currently, but without any user cues.
Selecting Edit Trip Details or Trip Summary can also zoom to current trip before launching the respective dialogs. So no matter what you select, the map will zoom to the entire trip.

**Comment by aesculus** [comment]
Let me think about this. I don't really like the idea of having to select something else to zoom my whole trip.

I don't really think Edit Trip Details is going to get used as much as today once we fix some of the other issues we have identified.

If anything Trip Summary should be overloaded from the map icon.

**Comment by EVGrokker** [comment]
>If anything Trip Summary should be overloaded from the map icon.

That's an interesting idea.

**Comment by EVGrokker** [comment]
This discussion has clarified a couple of things for me.
1. The problem that I have with the long press on the globe icon, as currently implemented, is that you never know how long you need to press to zoom to the entire trip. If you could modify the long-press behavior so that the zooming to trip level occurred after n seconds, even though the user is still holding the button, that would solve the discoverability problem. This is consistent with iOS behavior - a long press or a force press will initiate the response, even if the user is still holding the button. That way they know they got it. 
2. Your suggestion to overload the folded map button with a long press is brilliant. That way both the globe and map buttons have short and long press behaviors. The globe presses are all about zoom level; the map presses are all about invoking inspectors, either the Segment Inspector (short) or the Trip Inspector (long).

**Comment by aesculus** [comment]
We need to decide what the primary is for each button and then the secondary. Because the folded map has the red circle on MST, does that influence what is primary?

The time right now on long press is .5 seconds, so if you tap it, it will be primary. Anything longer than .5 seconds is going to the long press.  I will have to see how will I can tweak it to action before the user releases it.

**Comment by EVGrokker** [comment]
I'd vote for:

**Globe Button**
- Short: Zoom to active segment
- Long: Zoom to active route (immediately upon crossing the threshold, even when user continues to hold button)

Map Button:
- Short: **Segment Summary** dialog (to become Trip Inspector) (same as current behavior)
- Long:  **Edit Trip Details** dialog

Rationale for Map button overload:
With a short press, you get to the list of segments in the current trip, of which there can be many. Eventually it should be possible to edit or delete a segment from that list. 
With a long press, you get the trip, of which there can only be one. Similarly, it should be possible to edit the trip details or delete the trip.
Since the current trip "owns" all its segments, it makes sense that a longer press gets you higher up the chain to the master element.

We need to see this in action, but I'm fairly certain this will make sense when implemented.

**Comment by aesculus** [comment]
Wait. I am getting confused by names. Doing too many things at once perhaps.

Just for me can you give me the names for these four things again:
- Dialog that shows the waypoints for the current segment
- Dialog that shows the segments for the current trip
- Dialog that allows you to edit the trip (Edit Trip Details)
- Dialog that allows you to edit the segment details (Edit Segment Details)

**Comment by EVGrokker** [comment]
I've been sketching diagrams to make sure I've got a handle on this. I'm confident that we're OK, just too many concurrent pending changes are confusing.

>Just for me can you give me the names for these four things again:
>1. Dialog that shows the waypoints for the current segment
>2. Dialog that shows the segments for the current trip
>3. Dialog that allows you to edit the trip details on Current Trips menu (Edit Trip Details)
>4. Dialog that allows you to edit the segment details on map menu (Edit Segment Details)

In all cases, I'm giving you the current names of these dialogs. There are pending discussions about changing some of them, but let's get the UI navigation working correctly first. So this is true as of v 1.1.4:

1. The dialog that shows waypoints for the current segment is called the **Segment Summary** dialog. It is invoked from the Plan menu | Segment Summary.
2. The dialog that shows the segments for the current trip is called the **Trip Segments** dialog. It is invoked by touching the folded map button (short press).
3. The dialog that allows you to edit details of the current trip is called the **Edit Trip Details** dialog. It is not currently implemented, but the proposal is to add that menu item to the Current Trips menu, modeling the dialog on the **Edit Segment Details** dialog. The proposal is to also enable access to the **Edit Trip Details** dialog by long-pressing the folded maps button on the Plan screen.
4. The dialog that allows you to edit the segment details of the active segments is called the **Edit Segment Details** dialog. It is currently accessed from Plan menu | Edit Segment Details. 

There are more details to be added (which I'm ready to provide), but hopefully the short and direct answers are what you need right now.

**Comment by aesculus** [comment]
Thanks. Now I can get moving on these things.

>The proposal is to also enable access to the Edit Trip Details dialog by long-pressing the folded maps button on the Plan screen.

This was the one that confused me. So it will be accessible from both places then?

I think I might move on this first, and then go and update the dialogs themselves.

**Comment by EVGrokker** [comment]
Yes, Edit Trip Details will be accessible from both places - consider this Plan screen accelerator, avoiding the need to switch over to the Current Trips panel to tweak the current trip.

**Comment by aesculus** [comment]
OK. But all you are tweaking is:
- Name
- Rating
- Date/Time
- Comments

**Comment by EVGrokker** [comment]
Yes, that's all for now. But we have an elegant path to the dialog for additional functionality.

**Comment by aesculus** [comment]
I have implemented the auto long press feature so all long taps will display the appropriate dialog after 3/4 seconds regardless of if the user has raised their finger or not.

I also added a long press for the folded map so it brings up the Edit Trip dialog.

Implemented in V1.2 (58)

**Comment by EVGrokker** [comment]
v 1.2.0 (58)
This is a welcome addition, but it needs an additional refinement: 
- With an active trip with more than one stop, touch folded map button to display the Trip Browser, displaying the destination.
- Touch and hold the destination to open the Segment Browser. Don't release the touch until the Segment Browser is displayed.
- The held touch (if you don't release soon enough) is subsequently interpreted as a request to show the first waypoint in the Segment Browser.

Logic is needed that will keep the Segment Browser open without interpreting the held touch as a request to continue on to the first waypoint, unless the user releases and re-touches.

**Comment by aesculus** [comment]
This might be highly dependant on the number of stops and the device layout. I could not get this to do this on the iPad because I think the list might have ended up in a different place.

None the less I think I can prevent this from occurring.  I keep a flag open that indicates the user is doing a long press. I can detect that and maybe skip the click event.

I put a potential fix in V1.2 (59) but since I cannot duplicate this you will need to let me know if it works.

**Comment by EVGrokker** [comment]
v 1.2.0 (59)

Still seeing the click-thru behavior on an iPhone 7+.

**Comment by aesculus** [comment]
I was able to duplicate this. I am on it.

**Comment by aesculus** [comment]
Fixed in V1.2 (60)

**Comment by EVGrokker** [comment]
v 1.2.0 (60)

I'm still seeing the click-thru behavior on an iPhone 7+.

>Car Data: X90D, Charger: 48, Wheels: 20, Tires: 0, Pano: 0, 5 Seat: 1, Rear CC: 0, Bat Life: 100, Payload: 100, PF: 0, SA: 0, Temp: 20 
Device Info: iPhone; CPU iPhone OS 10_3_3 like Mac OS X 
Settings: Reserve SoC:20, Default SoC: 90, Region: 0, Units: 0 
Version: 1.2.0 (60) 
IAP: Pro:1, Sub:1 
Location: Unknown 
Trip: Springfield Supercharger, [awyg8y4cnxp3j4balao6yt]

1. Open the Trip Browser
2. Touch and hold the Petaluma Supercharger leg
3. The underlying stop (Grants Pass) receives a touch event and displays.

**Comment by aesculus** [comment]
Rats. I'll have to snag the iPhone and use this trip.  I was able to duplicate it on the iPad and thought I found the cause (it did not appear to be a click under as much as a persistent hold).  Maybe there is two problems here.

**Comment by aesculus** [comment]
This time for sure, V1.2 (61)

**Comment by EVGrokker** [comment]
Confirmed. Click-thru events are disabled.

**Comment by aesculus** [comment]
Turns out I broke the Trip Browser with this fix. So while it does not click through, most of the time the selection on the Trip Browser does not switch segments.

**Comment by aesculus** [comment]
Lets try this again with 1.2 (63).

**Comment by EVGrokker** [comment]
Looks good to me.
