### ISSUE TITLE
Location button and Globe button not aligned

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#311]
v 1.2 (2)

The Location button (upper left) and Globe button (upper right) are not vertically aligned on an iPhone. See attached screen shot.

![button alignment](https://cloud.githubusercontent.com/assets/26678403/25332522/0d1d6f2e-28a4-11e7-902c-bc10d4ffdaf1.PNG)

**Comment by aesculus** [comment]
Fixed in V1.2 (3)

**Comment by EVGrokker** [comment]
v 1.2 (3)
Not fixed on iPhone in v 1.2 (3).

![seattle-sb](https://cloud.githubusercontent.com/assets/26678403/25405396/6e71e33c-29c0-11e7-953c-0399ba056e41.PNG)

**Comment by aesculus** [comment]
Fixed in V1.2 (6). Move all buttons to the right.

Do we want to turn the map type button (map/satellite) buttons back on again?

**Comment by EVGrokker** [comment]
I'd recommend leaving it disabled in 1.1.5, wait to see if anyone squawks. Easy to put back if there's a compelling reason, but better to be rid of it for a cleaner UI.

**Comment by EVGrokker** [comment]
Button appearance now looks good. Closing this issue.
