### ISSUE TITLE
Filtering chargers to HPWC only leads to error dialog

### ISSUE THREAD

**Issue by EVGrokker** [aesculus/EVTO-App-Feedback#319]
v 1.2 (2)
**Summary**:
Selecting only Tesla HPWC chargers in the Filter Chargers dialog, then enabling the charger overlay leads to an error dialog.

**Detail**:
I consulted the [Tesla Destination charging map for Santa Barbara](https://www.tesla.com/findus#/bounds/34.4611451,-119.63992009999998,34.3952424,-119.76421390000002?search=destination%20charger,&name=Santa%20Barbara,%20CA,%20USA), then opened EVTO to see which (if any) of those chargers were in EVTO's database.

I set the Filter Chargers dialog to HPWC only:

![filter chargers](https://cloud.githubusercontent.com/assets/26678403/25380976/646d2abe-296f-11e7-8a10-866e2812eacc.PNG)

Next, I touched the plug button to show an overlay of chargers in the area, leading to this error dialog.

![filter error](https://cloud.githubusercontent.com/assets/26678403/25381055/99b1a88a-296f-11e7-8d24-87cd1cfcca60.PNG)

**Comment by aesculus** [comment]
I need to do some more work on the filter wrt HPWC. Right it appears to be more of a filter for the NREL chargers than for the Tesla supplied chargers. And given Tesla's latest push to increase destination charging, this will be even more important.

Plus in non NA regions that are lot more HPWC in the Tesla supplied list. Unfortunately most contain a restriction like being a paid guest, so they are worthless from an auto-routing perspective.

**Comment by EVGrokker** [comment]
Maybe useless for auto-routing, but I don't agree that it's useless from an user's perspective.  I'm working on a Destination Charging tutorial #322. The reason I created this issue was because I was doing a preliminary survey of Bend, Santa Rosa and Santa Barbara destination chargers from within EVTO, with the intent of switching over to Tesla's Find Use page to learn more about the individual sites.

**Comment by aesculus** [comment]
I added the feature to have the Charger Filter toggle HPWC on/off and to display them or not when the user selects the Tesla Charger icon from the map. Added in V1.2 (22)

**Comment by EVGrokker** [comment]
1.2.0 (22)

Tried displaying filters, I'm seeing this error:



G

**Comment by aesculus** [comment]
> Tried displaying filters, I'm seeing this error:

Picture did not come through

**Comment by aesculus** [comment]
![image](https://cloud.githubusercontent.com/assets/283364/26473267/596eb742-415f-11e7-91d6-d93bb2642bb0.png)

**Comment by aesculus** [comment]
Fixed in V1.2 (23)

**Comment by EVGrokker** [comment]
v 1.2.0 (42)

There's still an issue here.

- Open the Filter Chargers dialog, select only **Tesla HPWC (Level 2)**
- Save
- Dialog is displayed: "You have not chosen any non-Tesla superchargers to display…"

Either HWPC chargers should not be included in this list, or the error should not occur.

**Comment by aesculus** [comment]
See the discussion in #332 .

It's working correctly but perhaps the wording could be clearer.

**Comment by EVGrokker** [comment]
Let me be sure I understand. 

We have a Filter Chargers dialog which manages the display of all non-Superchargers (via NREL), plus HPWCs. The dialog is tied to the electrical outlet button on the Plan map - a long press opens the dialog to filter which type of chargers are displayed. (The FC dialog is also available from the Plan menu.)

HPWC chargers are included in this list, even though they're not part of the NREL database. This leads to the error cited in this issue and #332.

I see two possible solutions:
1. Remove HWPC from the Filter Chargers list. The display of HWPC chargers toggles on/off with the lighting bolt. All Tesla-specific chargers are toggled on/off as a group.
2. Remove HWPC from the Filter Chargers list. Create a 'Filter Tesla Chargers' dialog, invoked by a long-press on the lighting bolt, which allows the user to select among Superchargers and HWPCs. 

The logical grouping is that lightning bolt manages Tesla-specific chargers (SCs and HPWCs), and the outlet manages non-Tesla specific chargers.

I'm fine with either option, but not the status quo.

**Comment by EVGrokker** [comment]
Another way to rationalize grouping HWPCs with SCs is that the lightning bolt includes chargers that don't require the UMC. All outlet chargers require the UMC.

**Comment by aesculus** [comment]
That is the way it is, but the filter is supporting both sets (HPWC were an overlap and there is no filter for SC).

**Comment by aesculus** [comment]
> Remove HWPC from the Filter Chargers list. Create a 'Filter Tesla Chargers' dialog, invoked by a long-press on the lighting bolt, which allows the user to select among Superchargers and HWPCs.

This would be the only option with how it is structured today because only Tesla supplied chargers (SC and Destination Chargers - HPWC) are in the lightening bolt. I filtered out all those charges from the NREL db when requesting loads.

But think of a case where you get HPWC from some other source? What then?

**Comment by EVGrokker** [comment]
Consider the case of a HPWC charger that's not listed with Tesla, like say your house or my house. That's not any different than chargers that PlugShare knows about that NREL doesn't list. If the user knows about an HPWC that they intend to use, they simply declare it in the waypoint. It's no different than using PlugShare today.

We need to set user expectations about these charger overlays - it's a fast-growing list, and we're sourcing from the best data we have access to. But if they know of a specific charger they want to use, whether it's HPWC or 1772, they simply specify that when adding the waypoint and EVTO takes it from there. The only definitive list you can hope to have is SCs - HPWCs and non-Tesla chargers will always be sparse.

The predominant use of the lighting bolt will be to see where SCs are in an area you're thinking of driving through. I used it yesterday when trying to recreate the Business Insider route. There's no SC in Omaha, but there's one nearby in Council Bluffs. Bingo.

**Comment by aesculus** [comment]
> The predominant use of the lighting bolt will be to see where SCs are in an area you're thinking of driving through. 

Right now it's Tesla supplied chargers, both SC and Destination chargers. The Filter gets rid of the DC because they can be overwhelming. Wait until you see what the new Tesla list has in it.  Right now it's that way in Europe but coming to a continent near you.

Seems to me we can just change the message and satisfy the need. Or just dump the message altogether.  What you see is what you get. If you turn off all the chargers then don't expect to see any. The exception is the HPWC where they can get shown depending on what's in the filter setting. For SC they will always show if the lightening bolt is toggled.

**Comment by EVGrokker** [comment]
I think what you're advocating for is a unified Filter Chargers dialog.

I'm OK with that, with the following provisos:
- You segregate Tesla-specific chargers into a separate section
- You include SCs in the list of chargers that can be filtered
- A long press on the zap button displays the Filter Chargers dialog, just like a long-press on the outlet button.

![filter chargers](https://user-images.githubusercontent.com/26678403/27282022-869acc74-54ab-11e7-8b21-cdf419c4c8c4.jpg)

**Comment by aesculus** [comment]
Just to be clear:
- The charger filter will just do that, filter. So if you have nothing selected, nothing will show, no matter what state the lightening bolt or plug icons are in.
- The Tesla chargers (HPWC, HPWC-2, SC) will set what is shown in the lightening bolt icon when triggered
- The other chargers will show only when the plug icon is triggered

I could merge the J1772 and HPWC into one entry each since I really don't have a means to figure out which are whic from NREL or Tesla. There is a chance that the Tesla supplied HPWC could be determined to be over/under 9 kW, but the data so far is inconsistent at best. NREL only knows level and not power.

**Comment by EVGrokker** [comment]
With respect to the error message:
Option 1) If the user touches either the zap or outlet button, but the currently selected set of chargers for that button is empty, display a message "No chargers enabled for display. Use the <strong>Filter Chargers</strong> dialog to select chargers to be displayed.", with an OK button which closes the dialog and returns them to the Plan screen.

Option 2) Warn user before leaving the Filter Chargers dialog that they have disabled all chargers for either the zap or the outlet buttons. They may click OK, get distracted, or switch away from EVTO and forget about it until a couple of weeks later when they file a grievance.

I vote for Option 1. It's most likely to prevent user confusion in the event that they somehow end up with no chargers enabled.

My other suggestions remain:
- Group Tesla-specific chargers together at the top
- Enable a long-press on the zap icon to display the Filter Chargers dialog.

**Comment by aesculus** [comment]
Is option 1 and 2 overkill?

**Comment by EVGrokker** [comment]
>Is option 1 and 2 overkill?
No, certainly not. I always try to temper my suggestions with respect for your time. Option 2 is slightly more work, because to do it right, you need to specify which class of chargers are completely disabled, Tesla-specific or generic (or both). That's another reason why I think grouping HPWC with SCs is important.

"You have disabled display of all [Tesla] charging locations. Proceed?"

In that message, you would include 'Tesla' if they've disabled both SCs and HPWCs. If they've disabled all generics, the sentence reads "…display of all chargers…". If they've disabled all chargers in both categories, the the sentence reads the same as generic, "…display of all chargers…".

**Comment by aesculus** [comment]
Here is the proposed filter dialog:

![image](https://user-images.githubusercontent.com/283364/27298672-6c8c241c-54de-11e7-976e-7799470f0378.png)

**Comment by EVGrokker** [comment]
Looks good.

**Comment by aesculus** [comment]
Completed in V1.2 (45) except for the long press on zap icon. Next build for that.

**Comment by aesculus** [comment]
In V1.2 (46) the messages have been updated and the long press brings up the Charger Filter dialog.

All filters now apply to both Tesla and NREL chargers.
